### ISSUE TITLE
Not returining weather data

### ISSUE THREAD

**Issue by st3inar** [tverilytt/NODE-Red#1]
When using data from geonames (search place)node directly into weather info node (yr) as suggsted in the "Node-RED Geonames-Yr sample flow" example it returns unknown data.

Are these yr-nodes working correctly?

**Comment by tverilytt** [comment]
Hi!
Do you have an example flow?
Yr does not have weather information for arbitrary geolocations, if no weather information is found for a particular geolocation, an "unknown" message is returned.

Cheers
-jo

**Comment by st3inar** [comment]
Sorry for the typo earlier.

Here´s the flow:

![skjermbilde 2017-10-17 kl 22 18 47](https://user-images.githubusercontent.com/7063669/31687361-4e0509dc-b389-11e7-8e3e-4eb87d0f1134.png)

**Comment by tverilytt** [comment]
I think this is as expected. Not all geopositions or Geonames place names map to a Yr weather information place / station.
I use the Yr and Geonames nodes myself in my Google Maps mashup, to show current weather and Meteogram at chosen locations. You can check it out here:
http://jo2maps.mybluemix.net/map

You can drag the "bule ball" marker around to desired location, or write a place name in the search field. Or use the search field to go to a desired latitude,longitude position. I see that 63.43049,10.39506 do give Yr weather info & Meteogram.

Can you share what is the input to the Geonames "search place" node?
It preferably should have style "full" to return as much details as possible.

Cheers
-jo

**Comment by rpeders** [comment]
I have problems using this. Darksky component works, but not yr.
i get this in the response: 
 <title>Fant ikke /place/Norway/Hordaland/Hordaland/Abbed-tj&#248;rna/forecast.xml</title>
i'm in norway and we have the letter æ.ø and å
i can either searh for Abbed-tjørna or Åsen to find my forecast and it seems yr.node doesnt support those.. (fun fact: yr.no is norwegian :P )

my coordinates: 60.21456443785895, 5.411138494323723

**Comment by tverilytt** [comment]
@rpeders Hi! Hm, if I use my Google Maps mashup:
http://jo2maps.mybluemix.net/map
and search for Abbed-tjørna, I can see the Yr meteogram, and that should use the Yr Node-RED nodes.
The URLs seems to be:
http://www.yr.no/place/Norway/Hordaland/Os/Abbed-tj%C3%B8rna/hour_by_hour.html
http://www.yr.no/place/Norway/Hordaland/Os/Abbed-tj%C3%B8rna/forecast.xml

So maybe you need to specify "Os" as second-level location, instead of "Hordaland"?

Cheers
-jo
